### ISSUE TITLE
Error trying to run hand_eye_calibration_client 

### ISSUE THREAD

**Issue by Minimartian** [roboception/rc_visard_ros#12]
Hi, i'm trying to run the hand_eye_calibration_client:

rosrun rc_hand_eye_calibration_client rc_hand_eye_calibration_client_node _host:="169.254.151.219"

but i'm getting this error:

[FATAL] [1552386737.035425622]: Client could not be created due to an error: type must be boolean, but is number

Any thoughts on what this could be?

Thanks

**Comment by flixr** [comment]
Could you please provide some more details so we can try to reproduce this and narrow it down?

* OS
* ROS version
* hand_eye_calibration_client version (official package or built from source)

**Comment by Minimartian** [comment]
Ubuntu 16.04 with ROS kinetic, using the current master branch of rc_visard_ros which I cloned and installed using cmake.

**Comment by flixr** [comment]
What firmware version of the rc_visard are you using?

**Comment by flixr** [comment]
@Minimartian friendly ping: Could you please tell us the firmware version you are using so we can reproduce and fix this bug?

**Comment by Minimartian** [comment]
Sorry for the delay in reply, we have "rc_visard_v1.0.8"

**Comment by flixr** [comment]
Thanks for the info.

Ah... that is really old ;-)

I think the problem is that in this old version bools were not returned correctly (which was fixed in v1.1.0).
However https://github.com/roboception/rc_visard_ros/commit/bc2df89675a61eecf853fdfeb48d6cf3d6164d2c should make it work with this old version as well.
So please update to latest master and check again.

But in any case I would strongly recommend to update the firmware image to the latest release:
https://doc.rc-visard.com/latest/en/maintenance.html#updating-the-firmware
https://roboception.com/en/download/

**Comment by Minimartian** [comment]
Thanks this fixed it! closing the issue
