### ISSUE TITLE
Setting System Time 

### ISSUE THREAD

**Issue by tdinesh** [roboception/rc_visard_ros#4]
Is there a way to set the System Time through ROS?

**Comment by flixr** [comment]
NTP is enabled by default, so if the rc_visard has an internet connection it should work automatically.
From image version v1.2 on it will also use NTP servers advertised by DHCP.

You can also synchronize the time via PTP (PrecisionTimeProtocol), you can enable this on the rc_visard via the `ptp_enabled` dynamic reconfigure parameter since https://github.com/roboception/rc_visard_ros/commit/42232c7d52fc76b43ea993b9c9e38b932b4345db
You will need to start a PTP master from the machine you want to sync time with.

**Comment by tdinesh** [comment]
Thanks! 
I am using the debian pakage for ROS Kinetic. Is there a plan to update it soon? 
2.0.0-0xenial-20180227-123254-0800

**Comment by flixr** [comment]
We have no fixed date for the next release. But it might be a while, at the very least until the next sync of ROS packages from shadow-fixed to the public repo (which is once every couple of weeks, with the last one yesterday).
In the meantime you'll have to build this package from source.

**Comment by tdinesh** [comment]
Ok. I have it compiled, but having issue with running ptpd in master mode from ubuntu. Any example/tested ptpd.conf file?

**Comment by flixr** [comment]
A simple `sudo ptpd --masteronly --foreground -i eth0` should do...

**Comment by tdinesh** [comment]
Great! That worked. Still would prefer to make it persistent. Maybe add this in README.md

**Comment by flixr** [comment]
Since dynamic reconfigure takes the initial value from the parameter server, you can just set `ptp_enabled` there (or as launch parameter) so it will turn it on when you start this driver.
