### ISSUE TITLE
Is it possible to output raw image?

### ISSUE THREAD

**Issue by tuandle** [roboception/rc_visard_ros#6]
Hi,
We 're sorry if this is not an appropriate way to ask for this product's features.
We are considering buying the rc_visard unit. However, reading your document we see that the rc_visard only output rectified images messages. Is it possible to get raw image message to use our own SLAM method?
Moreover, is it possible to get a small rosbag from the rc_visard so that we can have a rough view of quality of hardware synchronization?
Best regards.

**Comment by heikohimu** [comment]
It is better to ask questions about the product on info@roboception.de or, if you have already an rc_visard on support@roboception.de. Nevertheless, I will try to briefly answer your questions.

The rc_visard sends only the rectified images with up to 25 Hz. The raw images are not available, but the sensors are well calibrated and calibration can be checked using the Web GUI.

Synchronisation and timestamping of images and IMU data is done in an FPGA and very precise. I am not sure how you would check that in a ROS bag file.

**Comment by tuandle** [comment]
@heikohimu: thank you for your reply and again, we're sorry for this inappropriate approach to ask questions.
About checking data synchronization, you can have a quick look at a rosbag to have a rough qualitative view. For example, a rosbag from high-end VI sensor such as [skybotix](http://wiki.ros.org/vi_sensor) will give you this:
![well_synced](https://user-images.githubusercontent.com/18464308/40283776-35682cbe-5cc7-11e8-961b-4313dd69c41b.png)

And a rosbag from a moderate VI sensor such as [ironsides](https://www.perceptin.io/ironsides) will give you this:
![ok_synced](https://user-images.githubusercontent.com/18464308/40283783-658d7e26-5cc7-11e8-8568-3c1cb743b3cb.png)

You can notice the big difference between those 2 sensors. Obviously this is NOT a correct way to compare those sensors but it can still give some insights.

**Comment by heikohimu** [comment]
I see what you mean. Please note that in the timeline in rqt_bag shows the time when the data was stored in the bag, not the time when it was measured.

The timestamps of the images and IMU data (and everything that is derived from it like poses) of the rc_visard are the exact times of the measurement. There will always be one IMU measurement in the middle of the exposure time of an image and the timestamps of this IMU measurement and the corresponding images will match exactly. All measurements of the rc_visard are perfectly synchronised and timestamped.

Nevertheless, in a recorded bag file you would see that the IMU data arrives much before the image data, because the IMU data (and the poses derived from it) are send out with a very low latency. In contrast, images are rectified and transmitting of 1.2 MPixel images takes much more time than for a few bytes of IMU measurements. Thus, you might think that the sensor is not well synchronized, but in reality it is just different latencies that you would see. On the receiver side you should always use a ROS time synchronizer.

**Comment by flixr** [comment]
Closing this as the question is answered.
